### ISSUE TITLE
Bu001 - 중복된 typename을 사용하지 않아야 합니다.

### ISSUE THREAD

**Issue by MyeongWoonJang** [MyeongWoonJang/cpp-study#32]
`Jongjin's-studyroom`의
6c5f5bf8b9674f5adbeb632d3f940476fb801436 - `더블 링크드 리스트 클론 코딩` `Commit`에 대한 `Issue`입니다.

`LinkedList.h`

```cpp
5 template <typename T>
6 class CListNode
7 {
8 	template <typename T>
9 	friend class CLinkedList;

...
```

`T`라는 `typename`이 중복되어 `Compile`이 불가합니다.
`Visual Studio`에선 보통 두 개 이상의 `typename`을 사용할 때 `Tx`, `Ty`와 같이 구분합니다.

<div align="center"><image src="https://user-images.githubusercontent.com/73771162/193973323-03903d98-9482-4b2e-9a9e-d0fa307899ce.PNG"></div>

**Comment by Lcat12345** [comment]
비주얼 스튜디오에서는 컴파일에 전혀 문제가 없는데 고쳐야 할까요?
![image](https://user-images.githubusercontent.com/62102830/194047894-86397ea2-40ad-4115-9366-d635daf8ed0b.png)

**Comment by MyeongWoonJang** [comment]
> 

두 가지 가능성이 있습니다.
- 위 코드는 단순 `friend` 선언이기 때문에 안쪽 `T`를 사용할 일이 없어 `Visual Studio` 컴파일러가 영리하게 처리했다.
- 변수의 이름이 겹치는 경우처럼, 안쪽 범위의 `typename`을 우선 사용했다.

<br>

중첩 `template`을 사용할 때 바깥 범위의 `typename`과 안쪽 범위의 `typename`을 같은 것을 써서 좋을 것이 없습니다.
- 코드를 읽을 때 어떤 `typename`을 말하는 것인지 모호하게 느껴집니다.
- 저는 `gdb online debugger` `IDE`를 사용해 작업했는데, 이것은 컴파일러로 `gcc`를 이용합니다.   
  `C/C++`의 대표적인 컴파일러 `gcc`로 컴파일이 불가능하다면, 코드 수정을 고려해봐야겠죠.

  - 웬만하면 어떤 컴파일러를 쓰는 지와 무관하게 컴파일 가능한 게 좋습니다.

**Comment by Lcat12345** [comment]
수정 완료하였습니다. 템플릿을 쓴다는 것은 무척이나 까다롭군요.
이슈는 꼭 제가 닫아야 하는건가요?
그리고 이슈를 닫으면 더이상 여기 담긴 댓글을 볼수 없는건가요

**Comment by MyeongWoonJang** [comment]
그걸 처음에는 `Issue`를 작성한 사람(지금이라면 저)이 닫도록 해야겠다고 생각했는데,
`Commit Message`로 `Close #32` 과 같이 작성하면 `Issue`를 닫을 수 있다는 사실을 발견해서,
이 경우엔 `Commit` 작성자가 `Issue`를 닫는 게 효율적이니 어떻게 해야할지 고민입니다.
일단 이 `Issue`는 제가 닫겠습니다.
