### ISSUE TITLE
En001 코드 리팩터링 - assert와 if를 동시에 쓰지 않기를 권장합니다.

### ISSUE THREAD

**Issue by MyeongWoonJang** [MyeongWoonJang/cpp-study#33]
`Jongjin's-studyroom`의
6c5f5bf8b9674f5adbeb632d3f940476fb801436 - `더블 링크드 리스트 클론 코딩` `Commit`에 대한 `Issue`입니다.

`LinkedList.h`

```cpp
...

150	T front()const
151	{
152		if (empty())
153			assert(false);
154
155		return m_pBegin->m_pNext->m_Data;
156	}
157
158	T back()const
159	{
160		if (empty())
161			assert(false);
162
163		return m_pEnd->m_pPrev->m_Data;
164	}

...
```

- `assert`는 인자가 false이면 프로그램을 중단합니다.

  - `assert`는 단정하다라는 뜻으로, 인자인 `statement`가 항상 참임을 단정합니다.   
  단정문이라고 부르죠.

- 비슷한 예로 `expect`도 있습니다.

  - `expect`는 인자인 `statement`가 참일 것이 기대됨을 나타냅니다.

- `assert`, `expect`와 같은 함수들은 오류 검출 코드 작성 시 번거로운 `if`문 생성을 피하도록 해줍니다.   
  다음과 같이 개선할 수 있겠죠.

`LinkedList.h`

```cpp
	T front()const
	{
		assert(!empty());

		return m_pBegin->m_pNext->m_Data;
	}

	T back()const
	{
		assert(!empty());

		return m_pEnd->m_pPrev->m_Data;
	}
```

작은 변화지만 더 깔끔한 코드가 되었습니다.

**Comment by Lcat12345** [comment]
수정 완료했습니다.

**Comment by Lcat12345** [comment]
수정 완료했습니다.
