### ISSUE TITLE
Bu002. 템플릿 변수를 함수의 매개변수로 전달

### ISSUE THREAD

**Issue by Lcat12345** [MyeongWoonJang/cpp-study#38]
https://github.com/MyeongWoonJang/cpp-study/blob/62f17d091287dfdab0e90a9848f29d6b1444e3af/dataStructure/Project1/Project1/main.cpp#L40-L41

https://github.com/MyeongWoonJang/cpp-study/blob/62f17d091287dfdab0e90a9848f29d6b1444e3af/dataStructure/Project1/Project1/main.cpp#L140-L146

`CLinkedList`에는 원소를 뒤에 추가할수있는 `push_back` 함수가 있습니다.

파일에서 데이터를 모두 읽어 `push_back`하는 기능을 가진 함수를 만들려고 합니다.

함수의 매개변수를 `CLinkedList<_T>& _Linkedlist`으로 정의하였으나   
`main`에서와는 달리 `push_back` 함수를 호출할 수 없었습니다.   

어떻게 해야할까요.

**Comment by MyeongWoonJang** [comment]
https://github.com/MyeongWoonJang/cpp-study/blob/62f17d091287dfdab0e90a9848f29d6b1444e3af/dataStructure/Project1/Project1/main.cpp#L35-L36

https://github.com/MyeongWoonJang/cpp-study/blob/62f17d091287dfdab0e90a9848f29d6b1444e3af/dataStructure/Project1/Project1/main.cpp#L140-L146

### Function Signature
- `readData`의 `declaration`과 `definition`에서 `function signature`가 다릅니다.

  - `declaration`에서는 `void(const CLinkedList<_T>&)` 입니다.
  - `definition`에서는 `void(CLinkedList<_T>&)`입니다.

- `parameter`는 `const`, `mutable`, `volatile` 등의 `qualifier`가 붙은 것과 그렇지 않은 것을 구분합니다.

  - `qualifier`가 다르다면, 서로 다른 `function`이 되어버립니다.

### Generic Programming
- `template`을 사용한 이유가 없습니다.

  - `function` `body`에서는 `specialized`된 `data type` `Champion`을 사용하고 있습니다.
  - `generic`한 `data type` `_T`가 사용되지 않았죠.
 
- `function signature`만 고쳐도 `code`는 동작하겠지만, 이 부분 또한 고쳐야 합니다.

- `template specialization`을 사용할 수 있습니다.   
  이 경우, `code`는 다음과 같습니다.   
```cpp
// function template : 템플릿 함수가 아니라, 함수 템플릿이라고 외워두는 편이 좋을 겁니다.
// 함수 템플릿은 함수가 아닙니다.
template <typename _T>
void readData(CLinkedList<_T>& _Linkedlist);

// declaration
template<>
void readData(CLinkedList<Champion>& _Linkedlist);

// definition
template<>
void readData(CLinkedList<Champion>& _Linkedlist)
{	
     Champion c = { "Lenoa" ,120, 100, 20, 3 };

     _Linkedlist.push_back(c);
}
```

> `function template`의 `specialization`은 `compile` 시점에 이루어집니다.
>
> `function template`은 말그대로 `template`일 뿐이고, 실제 `function`이 아닙니다.
> `compile` 과정에서 해당 `function template`이 코드의 어디어디에서 `call`되는지를 파악하고,
> 그에 맞게 `instantiation`된 `function`을 생성합니다.
>
> `int`로 `call`되고, `char`로 `call` 되고, `double`로 `call`되면 총 3개의 `function`이 생기겠죠.
> `template parameter`에 들어가는 `data type`마다 하나씩 생깁니다.
>
> 그래서, `function template` 하나만 만들었는데,
> 엄청난 양의 `function`이 생성되어 `code bloating`이 발생하는 불상사도 있죠 ㅎㅎ.
>
> 우리가 명시적으로 `specialization` 해주는 방법도 있습니다.
> 그게 위에 적은 `code`지요.

- `template`을 포기할 수 있습니다.
  이 경우, `code`는 다음과 같습니다.

```cpp
// declaration
void readData(CLinkedList<Champion>& _Linkedlist);

// definition
void readData(CLinkedList<Champion>& _Linkedlist)
{	
     Champion c = { "Lenoa" ,120, 100, 20, 3 };

     _Linkedlist.push_back(c);
}
```

**Comment by Lcat12345** [comment]
해결하였습니다. 혹시 이슈 해결시에 원하는 코멘트 형식이 있나요?

**Comment by MyeongWoonJang** [comment]
[Commit으로 Issue 닫기](https://github.com/MyeongWoonJang/cpp-study/blob/main/docs/work_tips.md#%EC%BB%A4%EB%B0%8B-%EB%A9%94%EC%8B%9C%EC%A7%80%EB%A1%9C-%EC%9D%B4%EC%8A%88-%EB%8B%AB%EA%B8%B0)가 가능합니다.

여기서 `Issue`를 `Close`한다면, 어떤 `Commit`으로 해결하였는지 링크해두면 좋을 것 같습니다.

**Comment by Lcat12345** [comment]
79d9bfb2ae4c678008af32d3d4e4a7b7e3c6252a 이슈 해결
